"""SFT + on-policy distillation data and loss helpers.

The hybrid condition deliberately uses two different sample populations in the
same optimizer step:

* ``training_mode=opd`` samples are generated by the current student and use
  the ordinary sampled reverse-KL OPD advantage;
* ``training_mode=sft`` samples contain a supervised conversation and use
  token-level negative log likelihood on its assistant spans.

This distinction matters: applying NLL to tokens sampled by the student itself
would be entropy minimization, not supervised fine-tuning.
"""

from __future__ import annotations

from argparse import Namespace
from typing import Any

import torch

from slime.utils.mask_utils import MultiTurnLossMaskGenerator
from slime.utils.ppo_utils import compute_policy_loss
from slime.utils.processing_utils import load_tokenizer
from slime.utils.types import RolloutBatch, Sample

from .opd import _teacher_log_probs

_MASK_GENERATORS: dict[tuple[str, str], tuple[Any, MultiTurnLossMaskGenerator]] = {}
VALID_MODES = {"opd", "sft"}


def training_mode(metadata: dict[str, Any] | None) -> str:
    mode = str((metadata or {}).get("training_mode", "opd")).lower()
    if mode not in VALID_MODES:
        raise ValueError(f"Unknown hybrid training_mode={mode!r}; expected one of {sorted(VALID_MODES)}.")
    return mode


def _mask_generator(args: Namespace) -> tuple[Any, MultiTurnLossMaskGenerator]:
    key = (str(args.hf_checkpoint), str(args.loss_mask_type))
    cached = _MASK_GENERATORS.get(key)
    if cached is None:
        tokenizer = load_tokenizer(args.hf_checkpoint, trust_remote_code=True)
        cached = (tokenizer, MultiTurnLossMaskGenerator(tokenizer, tokenizer_type=args.loss_mask_type))
        _MASK_GENERATORS[key] = cached
    return cached


def make_sft_sample(args: Namespace, sample: Sample) -> Sample:
    """Turn a full supervised conversation into a trainable ``Sample``."""

    if not isinstance(sample.prompt, list):
        raise TypeError(
            "SFT sources must use `apply_chat_template: false` and provide a list of messages; "
            f"got {type(sample.prompt).__name__}."
        )
    tokenizer, mask_generator = _mask_generator(args)
    tools = (sample.metadata or {}).get("tools")
    token_ids, full_loss_mask = mask_generator.get_loss_mask(sample.prompt, tools=tools)
    if len(token_ids) != len(full_loss_mask):
        raise ValueError(
            "Hybrid SFT token/mask length mismatch: " f"tokens={len(token_ids)}, mask={len(full_loss_mask)}."
        )
    response_length = mask_generator.get_response_lengths([full_loss_mask])[0]
    if response_length <= 0:
        raise ValueError("Hybrid SFT sample has no trainable assistant tokens.")

    sample.tokens = token_ids
    sample.response_length = response_length
    sample.loss_mask = full_loss_mask[-response_length:]
    sample.response = tokenizer.decode(token_ids[-response_length:], skip_special_tokens=False)
    sample.reward = 0.0
    sample.status = Sample.Status.COMPLETED
    sample.train_metadata = {"training_mode": "sft"}
    # The mixed path recomputes policy log-probs in Megatron for both sample
    # types.  Keeping rollout-side log-probs on only half of the rows would make
    # the default converter order-dependent.
    sample.rollout_log_probs = None
    return sample


def post_process_sft_opd_rewards(
    args: Namespace,
    samples: list[Sample],
    **kwargs: Any,
) -> tuple[list[float], list[float]]:
    """Extract teacher scores only for OPD rows and mark SFT rows explicitly."""

    del kwargs
    for sample in samples:
        mode = training_mode(sample.metadata)
        sample.train_metadata = {"training_mode": mode}
        sample.rollout_log_probs = None
        if mode == "opd":
            response = sample.get_reward_value(args)
            if not isinstance(response, dict):
                raise TypeError("An OPD row in sft_opd did not receive an SGLang teacher response.")
            sample.teacher_log_probs = _teacher_log_probs(response, sample.response_length)
        else:
            # These placeholders are replaced with the detached current-student
            # log-probs by ``hybrid_advantages``.  Consequently the default OPD
            # adjustment is exactly zero on SFT rows.
            sample.teacher_log_probs = torch.zeros(sample.response_length, dtype=torch.float32)

    zeros = [0.0] * len(samples)
    return zeros, list(zeros)


def _metadata_modes(metadata: list[dict[str, Any]] | None, expected: int) -> list[str]:
    if metadata is None or len(metadata) != expected:
        count = 0 if metadata is None else len(metadata)
        raise ValueError(f"sft_opd requires one training metadata entry per sample; got {count}, expected {expected}.")
    return [training_mode(item) for item in metadata]


def hybrid_advantages(args: Namespace, rollout_data: RolloutBatch) -> None:
    """Initialize pure-OPD advantages while masking OPD off SFT samples.

    Slime invokes this custom function before its standard OPD adjustment.  We
    replace the SFT rows' teacher scores by the current student scores, making
    their sampled reverse KL exactly zero.  OPD rows retain their real teacher
    scores.  All task rewards are zero in this condition.
    """

    student_log_probs = rollout_data.get("log_probs")
    teacher_log_probs = rollout_data.get("teacher_log_probs")
    if not student_log_probs or teacher_log_probs is None:
        raise ValueError("sft_opd requires current student and external teacher log-probs.")
    modes = _metadata_modes(rollout_data.get("metadata"), len(student_log_probs))
    if len(teacher_log_probs) != len(student_log_probs):
        raise ValueError("sft_opd teacher/student sample counts differ.")

    adjusted_teacher = list(teacher_log_probs)
    advantages: list[torch.Tensor] = []
    for index, (mode, student) in enumerate(zip(modes, student_log_probs, strict=True)):
        advantages.append(torch.zeros_like(student, dtype=torch.float32))
        if mode == "sft":
            adjusted_teacher[index] = student.detach()
    rollout_data["teacher_log_probs"] = adjusted_teacher
    rollout_data["advantages"] = advantages
    rollout_data["returns"] = [advantage.clone() for advantage in advantages]


def _mode_token_masks(modes: list[str], log_probs: list[torch.Tensor]) -> tuple[torch.Tensor, torch.Tensor]:
    opd = torch.cat(
        [torch.full_like(log_prob, float(mode == "opd")) for mode, log_prob in zip(modes, log_probs, strict=True)]
    )
    sft = 1.0 - opd
    return opd, sft


def hybrid_loss_function(
    args: Namespace,
    batch: RolloutBatch,
    logits: torch.Tensor,
    sum_of_sample_mean,
) -> tuple[torch.Tensor, dict[str, torch.Tensor]]:
    """Combine clipped OPD policy loss and supervised NLL in one step."""

    # Keep Megatron imports off rollout-manager processes, which import this
    # module only to construct supervised samples.
    from slime.backends.megatron_utils.loss import get_log_probs_and_entropy

    response_lengths = batch["response_lengths"]
    total_lengths = batch["total_lengths"]
    _, output = get_log_probs_and_entropy(
        logits,
        args=args,
        unconcat_tokens=batch["unconcat_tokens"],
        total_lengths=total_lengths,
        response_lengths=response_lengths,
        with_entropy=False,
    )
    log_prob_list = output["log_probs"]
    modes = _metadata_modes(batch.get("metadata"), len(log_prob_list))
    log_probs = torch.cat(log_prob_list, dim=0)
    advantages = torch.cat(batch["advantages"], dim=0)
    old_log_prob_list = batch.get("log_probs")
    if not old_log_prob_list:
        old_log_prob_list = [value.detach() for value in log_prob_list]
    old_log_probs = torch.cat(old_log_prob_list, dim=0)

    ppo_kl = old_log_probs - log_probs
    policy_tokens, clipfrac_tokens = compute_policy_loss(
        ppo_kl,
        advantages,
        args.eps_clip,
        args.eps_clip_high,
        eps_clip_c=args.eps_clip_c,
    )
    opd_mask, sft_mask = _mode_token_masks(modes, log_prob_list)
    opd_policy_loss = sum_of_sample_mean(policy_tokens * opd_mask)
    sft_loss = sum_of_sample_mean(-log_probs * sft_mask)
    opd_coef = float(args.hybrid_opd_loss_coef)
    sft_coef = float(args.hybrid_sft_loss_coef)
    loss = opd_coef * opd_policy_loss + sft_coef * sft_loss

    if log_probs.numel() == 0:
        loss = loss + 0 * logits.sum()
    return loss, {
        "loss": loss.detach().clone(),
        "opd_policy_loss": opd_policy_loss.detach().clone(),
        "sft_loss": sft_loss.detach().clone(),
        "ppo_kl": sum_of_sample_mean(ppo_kl * opd_mask).detach().clone(),
        "pg_clipfrac": sum_of_sample_mean(clipfrac_tokens * opd_mask).detach().clone(),
        "opd_sample_fraction": sum_of_sample_mean(opd_mask).detach().clone(),
        "sft_sample_fraction": sum_of_sample_mean(sft_mask).detach().clone(),
    }
